dist: xenial
language: python

jobs:
  include:
  - python: "3.6"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.7"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.8"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.9"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.6"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'
  - python: "3.7"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'
  - python: "3.8"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'
  - python: "3.9"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'


services:
  - mongodb
  - mysql
  - postgresql

install:
  # Setup
  - pip install -U atom motor sqlalchemy aiomysql aiopg

  # Testing
  - pip install -U codecov pytest pytest-coverage pytest-asyncio faker

  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov atomdb --cov-report xml

after_success:
  - codecov
