dist: bionic
language: python

jobs:
  include:
  - python: "3.8"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.9"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.10"
    env: DATABASE_URL='mysql://travis:@127.0.0.1:3306/test_atomdb'
  - python: "3.8"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'
  - python: "3.9"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'
  - python: "3.10"
    env: DATABASE_URL='postgres://postgres:@127.0.0.1:5432/test_atomdb'

services:
  - mongodb
  - mysql
  - postgresql

install:
  # Setup
  - pip install -U atom motor aiomysql aiopg
  - pip install -U 'sqlalchemy<1.4'

  # Testing
  - pip install -U codecov pytest pytest-coverage pytest-asyncio faker mypy isort black

  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov atomdb --cov-report xml
  - mypy atomdb --ignore-missing-imports
  - black atomdb --check --diff
  - isort atomdb --check --diff

after_success:
  - codecov
